- src/application.ini
- src/modules/slLauncher.jsm
Bump firefox/xulrunner to 37.* and fix "Permission denied to access property CoffeeScript" by defining the CoffeeScript var in the sandbox before running the loaded coffee-script code. #334
> Fix for "Permission denied to access property CoffeeScript"

- src/slimerjs
When we use `--debug*`, the `HIDE_ERRORS` is not set to `'N'` because it is in conjunction with `--*errors*`. This must be a disjunction here. So we fix that.
Also, we prevent any potential breaking when comparing the input against `--debug*` by surrounding `$i` with double-quotes.
> Fix `HIDE_ERRORS` switcher

- docs/api/webpage.rst
- src/modules/slimer-sdk/net-log.js
Done in the same way as Mozilla devtools (toolkit/devtools/webconsole/network-monitor.js NM__httpResponseExaminer())
This is something we will use to see if the response is HTTP/1.x or HTTP/2.
I haven't looked through all documentation, may need to be added somewhere else also.
> Extract and add HTTP protocol version to the response object

- src/application.ini
- src/modules/slLauncher.jsm
Hi,
This PR updates the version restriction to 40.* and fixes the 'Sandbox must subsume sandboxPrototype' error by supplying the content window as prototype if the version is 40 or above.
I have tested it with Firefox 40.0 and it seems to work.
> Gecko 40.* support and fix for 'Sandbox must subsume sandboxPrototype'

- buildpackage.sh
**XULRunner 40.0.3** contains a few fixes, especially for some vulnerabilities discovered in 40.0.2 - [more info](https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/#firefox40.0.3).
BTW, shouldn't SlimerJS use current ESR version of XULRunner? 38.x.x branch is going to be supported until May 2016 (currently, the newest ESR version is **38.2.1esr**).
> Bump XULRunner version to 40.0.3

- src/slimerjs.bat
On Windows, if slimerjs.bat is in a folder with a space in the path, slimerjs fail to launch.
This change fixed it for me.
> Fix when the path contains spaces on windows.

- docs/installation.rst
As promised, some documentation extension for "how to run add-ons" with SlimerJS. Thanks for your support on nailing it down.
> (add) documentation details for running add-ons

- src/modules/slConsole.jsm
- test/test-slConsole.js
Hello,
I have modified src/modules/slConsole.jsm so that console.log/info/warn/... can take multiple arguments as it should do according to the [API doc.] (https://developer.mozilla.org/en-US/docs/Web/API/Console/log)
> Fix console.log so it can take multiple arguments

- src/application.ini
- src/modules/slimer-sdk/webpage.js
This is a quick (but working) fix for:
https://github.com/laurentj/slimerjs/issues/425
https://github.com/laurentj/slimerjs/issues/402
It is working fine with Firefox 44 (the latest on Ubuntu 15.04 in /usr/lib/firefox) now. I have tested this on OS X and Ubuntu 15.04. I am still seeing these "warnings" on the command line:
```
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to create a SkiaGL DrawTarget, falling back to software
[GFX1-]: Failed to create a SkiaGL DrawTarget, falling back to software
1454812739239 addons.xpi  ERROR startup failed: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIXPCComponents_Utils.isModuleLoaded]"
```
But they are not preventing SlimerJS from running correctly. My web font only works in Firefox 44 …
> Remove domWindowUtils.setCSSViewport call for Firefox 44 compatibility

- src/defaults/preferences/prefs.js
This will disable Telemetry which is currently enabled - if you run SlimerJS in GUI mode with -jsconsole before this commit, then after ~2 minutes you may see:
```
Error: 1467794239788	Toolkit.Telemetry	ERROR	TelemetryStorage::loadAbortedSessionPing - error removing ping: PingReadError JS Stack trace: PingReadError@TelemetryStorage.jsm:80:15 < TelemetryStorageImpl.loadPingFile<@TelemetryStorage.jsm:1440:13
Source File: resource://gre/modules/Log.jsm
Line: 749
```
> Disabled Telemetry.

- src/modules/addon-sdk/sdk/platform/xpcom.js
- src/modules/addon-sdk/sdk/util/uuid.js
- src/modules/addon-sdk/toolkit/loader.js
- src/modules/slimer-sdk/system.js
- src/modules/slimer-sdk/webpage.js
Thanks to this commit the following messages will not be displayed when using newer version of Firefox:
```
JavaScript warning: resource://slimerjs/addon-sdk/toolkit/loader.js, line 283: expression closures are deprecated
JavaScript warning: resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/slimer-sdk/system.js, line 26: expression closures are deprecated
JavaScript warning: resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/slimer-sdk/webpage.js, line 1553: expression closures are deprecated
JavaScript warning: resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/addon-sdk/sdk/platform/xpcom.js, line 24: expression closures are deprecated
JavaScript warning: resource://slimerjs/addon-sdk/toolkit/loader.js -> …
```
> Replaced found Expression closures to Arrow functions for Firefox 49 compatibility

- src/defaults/preferences/prefs.js
places.sqlite will grow by 500KB,  which is 10MB  by default. This will reduce the profile directory size from 12MB to <3MB during PDF and image conversion.
> Increase places.sqlite file size by 500KB which is 10MB by default.

- website/faq.html
It seems running SlimerJS headless on Mac using Xvfb depends on firefox-x11. The firefox-x11 port has been abandoned.
Refer to https://trac.macports.org/ticket/42087 for more context.
> Delete claim that SlimerJS can run headless on Mac

- src/modules/slConfiguration.jsm
Suppressing error if the Webapps module could not be loaded to allow running SlimerJS under control of Light: https://sourceforge.net/projects/lightfirefox/
Without this fix you will see the following errors if you run SlimerJS under control of [Light](https://sourceforge.net/projects/lightfirefox/):
```
JavaScript error: resource://slimerjs/slConfiguration.jsm, line 16: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
JavaScript error: chrome://slimerjs/content/slimerjs.js, line 23: ReferenceError: dumpex is not defined
```
For more info please read https://github.com/laurentj/slimerjs/issues/373
> Suppressing error if the Webapps module could not be loaded

- docs/api/webpage.rst
- src/components/nsPrompter.js
Fixed infinite recursion when connecting via proxy which requires an authentication but the authentication credentials were empty or incorrect. Now it will throw an resource error instead of trying to connect using
the same credentials over and over again.
Quick test using `mitmdump` tool from [mitmproxy](http://docs.mitmproxy.org/en/stable/install.html) package:
1. Run `mitmdump --ignore '.*' --singleuser 'correct_user:correct_password' --no-http2 -v`
2. Run SlimerJS using the following parameters:
- `--proxy='127.0.0.1:8080'`
- `--proxy='127.0.0.1:8080' --proxy-auth='wrong_user:wrong_password'`
- `--proxy='127.0.0.1:8080' --proxy-auth='correct_user:correct_password'`
Known issues:
- Request id will be set to `null` when calling `webpage.onResourceError()` callback.
- There is only one …
> Fixed infinite recursion when connecting via proxy which requires an authentication

- package.json
- src/phantom-protocol.js
Package.json needs a main script so we are able to require it from JS. This will allow its usage by other phantom drivers. Fixes #563.
> Add main script to package.json.

- src/slimerjs-node
On Windows, when calling casperjs with `--engine=slimerjs`, I get the following error:
```
Error: spawn C:\...\node_modules\slimerjs\src\slimerjs ENOENT
at exports._errnoException (util.js:1026:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:359:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
at Module.runMain (module.js:606:11)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3
```
This pull request checks if we're on Windows and then calls the `slimerjs.bat` instead of `slimerjs`. This change resolves the above error and CasperJS operates normally.
> Get Windows to call bat file instead of slimerjs command

- src/modules/addon-sdk/sdk/io/file.js
Fixed issue with fs.copyTree() method which was not creating the target directory when trying to copy an empty source directory.
> Fixed bug in fs.copyTree() method

- src/slimerjs.bat
This PR allows SLIMERDIR to be set using an environment variable and only use %~dp0 if not set.
I added this as I'm trying to use slimerjs with backstopjs and somehow %~dp0 is not pointing to the location of slimjerjs.bat, rather my cwd, which causes the application.ini not found error.  With this patch I've been able to use slimerjs successfully.
May help #506.
Original solution found at http://luksurious.me/2014/03/making-casperjs-work-with-slimerjs-on-windows/
Tested on Windows 10 x64.
> Allow SLIMERDIR to be set using an env var

- src/modules/webpageUtils.jsm
With a debug build of Firefox 58 I get the following fatal assertion "channel needs to have loadInfo to perform security checks". This also helps more tests pass on release builds of Firefox 58.
The fix is rather hacky, but unfortunately seems to be the best way to do it after talking with Christoph:
> it seems there is not an ultimate better solution to what you already came up with. You could rewrite the code to use NetUtil.asyncFetch() [1,2] but I am not sure if it's worth the effort. Besides, they use a very similar approach and transfer the loadInfo from a dummy channel to the newly created channel.
>
>Cheers,
>  Christoph
>
>[1] https://dxr.mozilla.org/mozilla-central/source/browser/extensions/mortar/host/pdf/ppapi-content-sandbox.js#211
>[2] …
> Add fake loadinfo to satisfy security checks.

- src/components/filePicker.js
- src/components/httpd.js
- src/modules/addon-sdk/sdk/platform/xpcom.js
- src/modules/addon-sdk/sdk/system.js
- src/modules/addon-sdk/sdk/url.js
- src/modules/slConsole.jsm
- src/modules/slExit.jsm
- src/modules/slUtils.jsm
- src/modules/slimer-sdk/webserver.jsm
As of Firefox 57, nsILocalFile has been removed. However, nsIFile can be used in its place. See [Bug 1375125](https://bugzilla.mozilla.org/show_bug.cgi?id=1375125) for details.
> Replace nsILocalFile with nsIFile

- src/modules/addon-sdk/sdk/deprecated/api-utils.js
In `addon-sdk/sdk/deprecated/api-utils.js` there is a `yield` statement but it's not inside a generator. Recent versions of Firefox (either 56 or 57 I think) correctly report `yield` as a reserved word and fail on this code. Presumably this function was supposed to be a generator function.
> Fix generator syntax

- src/modules/slimer-sdk/system.js
This is fix for issue #478 
The problem is caused by nodejs, when child process is created using child_process.spawn. In this case stdin/stdout is piped to a socket, but it's not accessible by the child process. I could reproduce it with a simple .js and sh file:
/dev/stdout: symbolic link to /proc/self/fd/1
/proc/self/fd/1: broken symbolic link to socket:[5891187]
I'm not sure it's a bug or a feature in nodejs, but it behaves like this since v4.0. So I suggest the best to do is not to reference /dev/stdin / /dev/stdout directly
This fix falls back to the "dump" implementation when the requested output is not available
> In case we can not open an output return the fallback implementation

- src/components/filePicker.js
This logic was updated recently for FF54+, but this line was incomplete and ended up breaking the file picker in FF53 and below. This corrects that issue so that the file picker works in all versions.
> Fix file picker logic for FF < v54

- src/application.ini
- src/modules/addon-sdk/sdk/clipboard.js
- src/modules/addon-sdk/sdk/url.js
- src/modules/slimer-sdk/phantom.jsm
Firefox v59 removes support for non-standard conditional catch clauses: https://developer.mozilla.org/en-US/Firefox/Releases/59#JavaScript_2. These have been replaced with the equivilent catch and conditional logic blocks.
I've also updated the `MaxVersion` from 58.* to 59.*
The tests pass the same way they have for previous version with 4 out of 399 tests failing (which have been failing for some time).
I'm submitting a separate PR to fix the Dockerfile for testing in TravisCI.
> Firefox v59 Compatibility

- src/modules/slimer-sdk/webpage.js
This patch modifies executeEventListener function to call page.onError
listener when there is an exception while executing any listener
callback function.  The modification checks to not call onError listener
recursively.
This patch allows user scripts to listen for any errors in onError
function callback. By default, the exception handler in
executeEventListener absorbs all errors and do not propagate them, which
may hang the execution script if its waiting for any callbacks to
finish.
Signed-off-by: Avadh Patel <avadh4all@gmail.com>
> Redirect exception to page.onError when executing other event-listeners

- Dockerfile
This causes the installation to fail whenever the Firefox version gets updated.
>  Remove specific Firefox version in Dockerfile

- examples/async_await.js
Just example of how to use async/await and form submission
Do you think this a good example how to benefit from using async/await?
* Error handling is little big because `phantom.defaultErrorHandler` didn't show stacktrace (it expect stack to be array of objects, but plain js has `error.stack` as a string)
* And `system.stderr.write` doesn't print anything, is it expected?
Output will be:
```
Loading: https://news.ycombinator.com/ 
Loaded https://news.ycombinator.com/  (success) 
LOG: Searching "Slimerjs" on HackerNews -- phantomjs://webpage.evaluate():5 
Loading: https://hn.algolia.com/?q=Slimerjs 
Waiting saerch results page to load 
...........Loaded https://hn.algolia.com/?q=Slimerjs  (success) 
.
Page content:
SlimerJS – A scriptable browser for Web developers
93 points T-A 3 years …
```
> Add async-await example

- test/test-webpage-keyevent-phantom.js
- test/test-webpage-keyevent2.js
There is a small typo in test/test-webpage-keyevent-phantom.js, test/test-webpage-keyevent2.js.
Should read `accentuated` rather than `accentued`.
> docs: Fix simple typo, accentued -> accentuated

- src/modules/slCookiesManager.jsm
Cookies obtained from page.cookies should now have an accurate 'expires' attribute.
The Date() constructor accepts milliseconds from epoch as its parameter, but nsCookie.expires is in seconds, leading to some wacky dates.
Would fix #718.
> Fix for cookie expires attribute
